
name: CI/CD Pipeline for AWS Databricks

on:
  push:
    branches:
      - main

jobs:
  databricks-pipeline:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # List files after checkout
    - name: List files
      run: ls -R

    # Install Databricks CLI
    - name: Install Databricks CLI
      run: pip install databricks-cli

    # Configure Databricks CLI
    - name: Configure Databricks CLI
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      run: |
        databricks configure --token <<EOF
        $DATABRICKS_HOST
        $DATABRICKS_TOKEN
        EOF

    # Deploy to Databricks
    - name: Deploy Notebooks
      run: |
        databricks workspace import_dir /home/runner/work/databricks-test/databricks-test /Workspace/Users/vikram.pandhyal@bitsinglass.com/myproject --overwrite
