
name: CI/CD Pipeline for AWS Databricks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  databricks-pipeline:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
   #  Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    #  Install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
  

    # List files after checkout
    - name: List files
      run: ls -R
    - name: List Files in Test Directory
      run: ls -R /home/runner/work/databricks-test/databricks-test/tests/

    # Install Databricks CLI
    - name: Install Databricks CLI
      run: pip install databricks-cli

    # Configure Databricks CLI
    - name: Configure Databricks CLI
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      run: |
        databricks configure --token <<EOF
        $DATABRICKS_HOST
        $DATABRICKS_TOKEN
        EOF
   
     # Step 4: Run tests
    - name: Run Tests
      run: pytest /home/runner/work/databricks-test/databricks-test/tests/

    # Deploy to Databricks
    - name: Deploy Notebooks
      run: |
        databricks workspace import_dir /home/runner/work/databricks-test/databricks-test /Workspace/Users/vikram.pandhyal@bitsinglass.com/myproject --overwrite
